/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/usr"
#define EXEC_PREFIX "/usr"
#define BINDIR "/usr/bin"
#define SBINDIR "/usr/sbin"
#define LIBEXECDIR "/usr/libexec"
#define DATAROOTDIR "/usr/share"
#define DATADIR "/usr/share"
#define SYSCONFDIR "/usr/etc"
#define SHAREDSTATEDIR "/usr/com"
#define LOCALSTATEDIR "/usr/var"
#define RUNSTATEDIR "/usr/var/run"
#define INCLUDEDIR "/usr/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/usr/share/doc/hello"
#define INFODIR "/usr/share/info"
#define HTMLDIR "/usr/share/doc/hello"
#define DVIDIR "/usr/share/doc/hello"
#define PDFDIR "/usr/share/doc/hello"
#define PSDIR "/usr/share/doc/hello"
#define LIBDIR "/usr/lib"
#define LISPDIR "/usr/share/emacs/site-lisp"
#define LOCALEDIR "/usr/share/locale"
#define MANDIR "/usr/share/man"
#define PKGDATADIR "/usr/share/hello"
#define PKGINCLUDEDIR "/usr/include/hello"
#define PKGLIBDIR "/usr/lib/hello"
#define PKGLIBEXECDIR "/usr/libexec/hello"
